# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  global:
    DATABASE_PASS: Password12!
  matrix:
    - PYTHON: "C:\\Python27"
      TOXENV: py27-dj19-postgres-noelasticsearch

    - PYTHON: "C:\\Python27"
      TOXENV: py27-dj19-mysql-noelasticsearch

services:
  - mysql               # start MySQL 5.6 service
  - postgresql          # start PostgreSQL 9.5 service


init:
  - "%PYTHON%/python -V"
  - "%PYTHON%/python -c \"import struct;print( 8 * struct.calcsize(\'P\'))\""

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install tox"


build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/tox"

after_test:
  - "%PYTHON%/python setup.py bdist_wheel"
  - ps: "ls dist"

artifacts:
  - path: dist\*
